[package]
name = "fr-docs"
version = "0.1.0"
edition = "2021"

[dependencies]
build_html = "2.4.0"
calamine = "0.24.0"
enum-map = "2.7.3"
lazy-regex = "3.1.0"
regex = "1.10.4"
reqwest = "0.12.4"
strum = { version = "0.26.2", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
